name: JSONAPI
main: com.alecgorge.minecraft.jsonapi.JSONAPI
version: 3.4.4
description: Control your server and fetch information from your server.
website: http://alecgorge.com/minecraft/jsonapi/
author: Alec Gorge
softdepend: [Vault, RemoteToolkitPlugin, dynmap]
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>
  calladmin:
    description: Sends a message to the admin of the server if they have Adminium installed on their iOS device.
    usage: /<command> <why>
permissions:
    jsonapi.calladmin:
        description: NOTE If you want to use this, make sure you set `anyone-can-use-calladmin` to false in config.yml. Allows users to send a push notification to the devices connected with Adminium.
        default: op