name: JSONAPI
main: com.ramblingwood.minecraft.jsonapi.JSONAPI
version: 3.0.0
description: Control your server and fetch information from your server.
website: http://alecgorge.com/minecraft/jsonapi/
author: Alec Gorge
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>