name: JSONAPI
main: com.alecgorge.minecraft.jsonapi.JSONAPI
version: 3.2.0
description: Control your server and fetch information from your server.
website: http://alecgorge.com/minecraft/jsonapi/
author: Alec Gorge
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>
  calladmin:
    description: Sends a message to the admin of the server if they have Adminium installed on their iOS device.
    usage: /<command> <why>