name: JSONAPI
main: com.ramblingwood.minecraft.jsonapi.JSONAPI
version: 1.7
description: Control your server and fetch information form your server.
website: http://ramblingwood.com/minecraft/jsonapi/
author: Alec Gorge
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>