name: JSONAPI
main: com.alecgorge.minecraft.jsonapi.JSONAPI
version: 3.7.7
description: Control your server and fetch information from your server.
website: http://mcjsonapi.com/
author: Alec Gorge
softdepend: [Vault, RemoteToolkitPlugin, dynmap]
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>
  calladmin:
    description: Sends a message to the admin of the server if they have Adminium installed on their iOS device.
    usage: /<command> <why>
  jsonapi:
    usage: '/<command> [list|reload|subscribe <source name> <url>|users [list|<username> password|add <username> <password>]]'
    description: 'Various commands to control JSONAPI. Check the docs for details: http://mcjsonapi.com/docs'
  adminium:
    usage: '/<command> [user (username)|create-user (username) (group name)|set-group (username) (group name)|list-groups]'
    description: 'Various commands to control Adminium''s permissions. Check http://mcjsonapi.com/docs/adminium for details.'
permissions:
  jsonapi.command:
    description: The ability to use the /jsonapi and /adminium commands
    default: false
  jsonapi.calladmin:
    description: 'NOTE If you want to use this, make sure you set `anyone-can-use-calladmin` to false in config.yml. Allows users to send a push notification to the devices connected with Adminium.'
    default: op